# Generated by Django 3.1.6 on 2021-07-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bModel',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
